title: "Mahdi Miri"
email: "mahdimiri7@gmail.com"
description: "ML / AI Engineer â€” Portfolio of Mahdi Miri"
baseurl: "" # change if you host at username.github.io/repo
url: ""      # put your site URL here if available, e.g. https://mahdi-miri.github.io
theme: minima
plugins: []
